version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
  test:
    build: .
    command: npm test
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=test